name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Display Environment Information
        run: go env

      - name: Install dependencies and run tests
        run: |
          mkdir -p coverage
          go mod tidy
          go mod download
          go test -v -covermode=atomic -coverprofile=coverage/cover.out ./...

      - name: Adjust coverage paths
        run: |
          TEMP_COVER_OUT=$(mktemp)
          echo "mode: set" > $TEMP_COVER_OUT
          sed 's#$(pwd)/##g' coverage/cover.out | grep -v "^mode:" >> $TEMP_COVER_OUT
          mv $TEMP_COVER_OUT coverage/cover.out

      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/cover.out
